/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    events: Event;
    orders: Order;
    tickets: Ticket;
    'account-groups': AccountGroup;
    'gl-accounts': GlAccount;
    'journal-entries': JournalEntry;
    parties: Party;
    documents: Document;
    'doc-sequences': DocSequence;
    items: Item;
    'stock-movements': StockMovement;
    tenants: Tenant;
    notifications: Notification;
    favorites: Favorite;
    members: Member;
    archives: Archive;
    messages: Message;
    'chat-rooms': ChatRoom;
    'membership-types': MembershipType;
    'bank-statements': BankStatement;
    'fixed-assets': FixedAsset;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    apikeys: Apikey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'account-groups': AccountGroupsSelect<false> | AccountGroupsSelect<true>;
    'gl-accounts': GlAccountsSelect<false> | GlAccountsSelect<true>;
    'journal-entries': JournalEntriesSelect<false> | JournalEntriesSelect<true>;
    parties: PartiesSelect<false> | PartiesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'doc-sequences': DocSequencesSelect<false> | DocSequencesSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    archives: ArchivesSelect<false> | ArchivesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'chat-rooms': ChatRoomsSelect<false> | ChatRoomsSelect<true>;
    'membership-types': MembershipTypesSelect<false> | MembershipTypesSelect<true>;
    'bank-statements': BankStatementsSelect<false> | BankStatementsSelect<true>;
    'fixed-assets': FixedAssetsSelect<false> | FixedAssetsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    apikeys: ApikeysSelect<false> | ApikeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ne' | 'new') | ('en' | 'ne' | 'new')[];
  globals: {
    header: Header;
    footer: Footer;
    'billing-settings': BillingSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'billing-settings': BillingSettingsSelect<false> | BillingSettingsSelect<true>;
  };
  locale: 'en' | 'ne' | 'new';
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Unique illaka code (e.g. IL01 … IL10). The central organization uses C00.
   */
  code?: string | null;
  /**
   * Central is the parent organization (code C00); everything else is an illaka.
   */
  type?: ('central' | 'illaka') | null;
  /**
   * Whether the illaka is active for accounting.
   */
  active?: boolean | null;
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * If checked, the tenant will be shown on the website. If not checked, the tenant will not be shown on the website.
   */
  enabled?: boolean | null;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  /**
   * Ilaka location details
   */
  location?: {
    /**
     * Physical address of the Ilaka
     */
    address?: string | null;
    /**
     * Google Maps Embed URL or Link
     */
    mapUrl?: string | null;
    /**
     * Latitude coordinate
     */
    latitude?: number | null;
    /**
     * Longitude coordinate
     */
    longitude?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage images and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  tenant?: (number | null) | Tenant;
  email: string;
  emailVerified?: boolean | null;
  name?: string | null;
  image?: (number | null) | Media;
  phoneNumber?: string | null;
  role?:
    | (
        | 'user'
        | 'admin'
        | 'super-admin'
        | 'central-treasurer'
        | 'central-auditor'
        | 'central-exec'
        | 'illaka-chair'
        | 'illaka-treasurer'
        | 'illaka-secretary'
        | 'illaka-accountant'
        | 'illaka-member-officer'
        | 'viewer'
      )
    | null;
  gender?: ('male' | 'female' | 'other' | 'prefer-not-to-say') | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  fcmTokens?:
    | {
        token: string;
        device?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-added by Better Auth (banned)
   */
  banned?: boolean | null;
  /**
   * Auto-added by Better Auth (banReason)
   */
  banReason?: string | null;
  /**
   * Auto-added by Better Auth (banExpires)
   */
  banExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Event location coordinates
   */
  location?: {
    /**
     * Location of the event location
     */
    location?: string | null;
    /**
     * Map address of the event location for google maps
     */
    'Map location'?: string | null;
    /**
     * Latitude coordinate of the event location
     */
    latitude?: number | null;
    /**
     * Longitude coordinate of the event location
     */
    longitude?: number | null;
  };
  startDatetime?: string | null;
  endDatetime?: string | null;
  relatedEvents?: (number | Event)[] | null;
  /**
   * Select one or more tags for this event
   */
  tags?:
    | (
        | 'music'
        | 'gaming'
        | 'theatre'
        | 'arts'
        | 'business'
        | 'technology'
        | 'sports'
        | 'food-drink'
        | 'exhibition'
        | 'comedy'
        | 'workshop'
        | 'fitness'
      )[]
    | null;
  /**
   * Enable or disable this event
   */
  enabled: boolean;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  buyer: number | User;
  event: number | Event;
  totalAmount?: number | null;
  status?: ('pending' | 'paid' | 'cancelled' | 'refunded') | null;
  tickets?: (number | Ticket)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  event: number | Event;
  order: number | Order;
  code?: string | null;
  status?: ('unused' | 'checked-in' | 'cancelled' | 'refunded' | 'transferred') | null;
  checkedInAt?: string | null;
  attendeeName?: string | null;
  attendeeEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-groups".
 */
export interface AccountGroup {
  id: number;
  code?: string | null;
  name: string;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  parent?: (number | null) | AccountGroup;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-accounts".
 */
export interface GlAccount {
  id: number;
  code?: string | null;
  name: string;
  group?: (number | null) | AccountGroup;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  /**
   * Cash/bank accounts drive the cash & bank book and reconciliation.
   */
  class?: ('cash' | 'bank' | 'other') | null;
  /**
   * Opening balance at the start of the books (debit positive).
   */
  openingBalance?: number | null;
  active?: boolean | null;
  allowManualPosting?: boolean | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries".
 */
export interface JournalEntry {
  id: number;
  date: string;
  /**
   * Description of the entry (e.g. "Rent for March", "Member donation").
   */
  narration?: string | null;
  status: 'draft' | 'posted' | 'void';
  postedAt?: string | null;
  /**
   * Marked by bank reconciliation when a matching bank-statement row is found.
   */
  cleared?: boolean | null;
  clearedAt?: string | null;
  lines: {
    account: number | GlAccount;
    /**
     * Amount on the debit side (leave empty if this is a credit line).
     */
    debit?: number | null;
    /**
     * Amount on the credit side (leave empty if this is a debit line).
     */
    credit?: number | null;
    memo?: string | null;
    id?: string | null;
  }[];
  createdBy?: (number | null) | User;
  tenant: number | Tenant;
  referenceDoc?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  docType:
    | 'sales-order'
    | 'sales-invoice'
    | 'purchase-order'
    | 'purchase-invoice'
    | 'payment-voucher'
    | 'receipt-voucher'
    | 'credit-note'
    | 'debit-note'
    | 'petty-cash-voucher'
    | 'grn'
    | 'delivery-challan'
    | 'journal-voucher'
    | 'membership-receipt'
    | 'donation-receipt';
  /**
   * Assigned automatically on posting (or on confirming an order).
   */
  number?: string | null;
  date: string;
  /**
   * Customer / vendor. Not used for journal vouchers.
   */
  party?: (number | null) | Party;
  /**
   * Description of the transaction.
   */
  narration?: string | null;
  status: 'draft' | 'posted' | 'void';
  postedAt?: string | null;
  /**
   * Order lifecycle. Only the confirm/cancel endpoints change this.
   */
  orderStatus?: ('draft' | 'confirmed' | 'cancelled') | null;
  confirmedAt?: string | null;
  cancelledAt?: string | null;
  /**
   * Journal entry created when this document was posted.
   */
  journalEntry?: (number | null) | JournalEntry;
  /**
   * Original document this note/challan refers to.
   */
  referenceTo?: (number | null) | Document;
  paymentMethod?: ('cash' | 'bank') | null;
  /**
   * Override the default bank account for this voucher.
   */
  bankAccount?: (number | null) | GlAccount;
  /**
   * Donation classification (per the income/fundraising taxonomy).
   */
  donationPurpose?: ('individual' | 'corporate' | 'community' | 'other') | null;
  lines?:
    | {
        /**
         * Inventory item (optional). When set, posting creates stock movements; GRN receives, sales invoices & challans issue at weighted-average cost.
         */
        item?: (number | null) | Item;
        description: string;
        qty?: number | null;
        rate?: number | null;
        /**
         * Line total. Computed as qty × rate if left empty.
         */
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  journalLines?:
    | {
        account: number | GlAccount;
        debit?: number | null;
        credit?: number | null;
        memo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tax rate in percent applied to the net total.
   */
  taxRate?: number | null;
  netTotal?: number | null;
  taxTotal?: number | null;
  grossTotal?: number | null;
  createdBy?: (number | null) | User;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties".
 */
export interface Party {
  id: number;
  type: 'customer' | 'vendor' | 'both';
  name: string;
  email?: string | null;
  phone?: string | null;
  /**
   * Tax registration / PAN number.
   */
  taxId?: string | null;
  address?: string | null;
  /**
   * Outstanding balance at the start of the books (positive = they owe you).
   */
  openingBalance?: number | null;
  /**
   * Mark as a donor to surface this party in donation reports.
   */
  donor?: boolean | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  /**
   * SKU / item code.
   */
  code?: string | null;
  name: string;
  /**
   * Unit of measure (pc, kg, box, litre…).
   */
  unit?: string | null;
  /**
   * AVCO is implemented; FIFO is planned.
   */
  valuationMethod: 'avco' | 'fifo';
  /**
   * Alert when on-hand stock drops below this.
   */
  reorderLevel?: number | null;
  /**
   * Starting quantity. Valued at the purchase price.
   */
  openingStock?: number | null;
  /**
   * Default selling price.
   */
  salePrice?: number | null;
  /**
   * Default purchase cost — also values the opening stock.
   */
  purchasePrice?: number | null;
  active?: boolean | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doc-sequences".
 */
export interface DocSequence {
  id: number;
  key: string;
  lastNumber: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  item: number | Item;
  /**
   * The voucher that caused this movement.
   */
  doc?: (number | null) | Document;
  date: string;
  /**
   * Quantity received into stock.
   */
  qtyIn?: number | null;
  /**
   * Quantity issued out of stock.
   */
  qtyOut?: number | null;
  /**
   * Unit cost at the time of the movement (AVCO).
   */
  unitCost?: number | null;
  location?: string | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  title: string;
  message: string;
  type?: ('info' | 'event' | 'reminder' | 'system') | null;
  read?: boolean | null;
  /**
   * Optional link to redirect the user (e.g. /events/123)
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  event: number | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  tenant?: (number | null) | Tenant;
  fullName: string;
  email: string;
  profileImage?: (number | null) | Media;
  /**
   * Short professional biography
   */
  bio?: string | null;
  role?: ('admin' | 'moderator' | 'member' | 'vip') | null;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    website?: string | null;
  };
  status?: ('active' | 'inactive' | 'suspended') | null;
  joinedDate?: string | null;
  phoneNumber?: string | null;
  /**
   * Unique Member ID from community records
   */
  memberId?: string | null;
  user?: (number | null) | User;
  expiryDate?: string | null;
  idCardDetails?: {
    bloodGroup?: string | null;
    emergencyContact?: string | null;
  };
  /**
   * Membership category (Basic, Standard, Premium, etc.)
   */
  membershipType?: (number | null) | MembershipType;
  /**
   * When the current membership period expires
   */
  renewalDate?: string | null;
  /**
   * Link to the latest membership fee receipt
   */
  lastReceipt?: (number | null) | Document;
  paymentStatus?: ('unpaid' | 'paid' | 'overdue') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types".
 */
export interface MembershipType {
  id: number;
  name: string;
  /**
   * Annual fee in NPR
   */
  fee: number;
  /**
   * Membership period in months (default 12 = annual)
   */
  periodMonths?: number | null;
  description?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archives".
 */
export interface Archive {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Historical era or period (e.g., 18th Century, Malla Era)
   */
  era?: string | null;
  year?: number | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  tenant?: (number | null) | Tenant;
  chatRoom: number | ChatRoom;
  sender: number | User;
  content: string;
  readBy?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms".
 */
export interface ChatRoom {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  type: 'direct' | 'group';
  members: (number | User)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-statements".
 */
export interface BankStatement {
  id: number;
  /**
   * The bank account this statement belongs to (GL account with class = bank).
   */
  account: number | GlAccount;
  periodStart?: string | null;
  periodEnd?: string | null;
  /**
   * Bank's stated opening balance for the period.
   */
  openingBalance?: number | null;
  /**
   * Bank's stated closing balance for the period.
   */
  closingBalance?: number | null;
  /**
   * Statement lines. Positive amount = deposit (money in), negative = withdrawal (money out).
   */
  rows?:
    | {
        date: string;
        description?: string | null;
        /**
         * Cheque no / transaction id / reference.
         */
        reference?: string | null;
        /**
         * Signed amount: + deposit, − withdrawal.
         */
        amount: number;
        /**
         * Journal entry this row was matched to by reconciliation.
         */
        matchedEntry?: (number | null) | JournalEntry;
        id?: string | null;
      }[]
    | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixed-assets".
 */
export interface FixedAsset {
  id: number;
  /**
   * Asset code / tag number.
   */
  code?: string | null;
  /**
   * Asset name (e.g. "Projector — Hall A").
   */
  name: string;
  /**
   * Asset category (drives reporting).
   */
  category?: ('vehicle' | 'equipment' | 'furniture' | 'computer' | 'building' | 'land' | 'other') | null;
  /**
   * Date the asset was acquired. Depreciation starts the following month.
   */
  purchaseDate?: string | null;
  /**
   * Purchase / acquisition cost.
   */
  purchaseCost: number;
  /**
   * Estimated residual value at end of useful life.
   */
  salvageValue?: number | null;
  /**
   * Straight-line useful life in years.
   */
  usefulLifeYears: number;
  /**
   * Where the asset is kept.
   */
  location?: string | null;
  status?: ('active' | 'disposed') | null;
  /**
   * Journal entries posted by the depreciation engine (read-only).
   */
  depreciationRows?:
    | {
        date: string;
        amount: number;
        journalEntry?: (number | null) | JournalEntry;
        id?: string | null;
      }[]
    | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      }
    | {
        relationTo: 'archives';
        value: number | Archive;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  eventDate?: string | null;
  location?: string | null;
  era?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: number | User;
  impersonatedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  accountId: string;
  providerId: string;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (apikey)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apikeys".
 */
export interface Apikey {
  id: number;
  name?: string | null;
  start?: string | null;
  prefix?: string | null;
  key: string;
  user: number | User;
  refillInterval?: number | null;
  refillAmount?: number | null;
  lastRefillAt?: string | null;
  enabled?: boolean | null;
  rateLimitEnabled?: boolean | null;
  rateLimitTimeWindow?: number | null;
  rateLimitMax?: number | null;
  requestCount?: number | null;
  remaining?: number | null;
  lastRequest?: string | null;
  expiresAt?: string | null;
  permissions?: string | null;
  metadata?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'account-groups';
        value: number | AccountGroup;
      } | null)
    | ({
        relationTo: 'gl-accounts';
        value: number | GlAccount;
      } | null)
    | ({
        relationTo: 'journal-entries';
        value: number | JournalEntry;
      } | null)
    | ({
        relationTo: 'parties';
        value: number | Party;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'doc-sequences';
        value: number | DocSequence;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'archives';
        value: number | Archive;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'chat-rooms';
        value: number | ChatRoom;
      } | null)
    | ({
        relationTo: 'membership-types';
        value: number | MembershipType;
      } | null)
    | ({
        relationTo: 'bank-statements';
        value: number | BankStatement;
      } | null)
    | ({
        relationTo: 'fixed-assets';
        value: number | FixedAsset;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null)
    | ({
        relationTo: 'apikeys';
        value: number | Apikey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  phoneNumber?: T;
  role?: T;
  gender?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  fcmTokens?:
    | T
    | {
        token?: T;
        device?: T;
        id?: T;
      };
  banned?: T;
  banReason?: T;
  banExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  content?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  location?:
    | T
    | {
        location?: T;
        'Map location'?: T;
        latitude?: T;
        longitude?: T;
      };
  startDatetime?: T;
  endDatetime?: T;
  relatedEvents?: T;
  tags?: T;
  enabled?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  buyer?: T;
  event?: T;
  totalAmount?: T;
  status?: T;
  tickets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  event?: T;
  order?: T;
  code?: T;
  status?: T;
  checkedInAt?: T;
  attendeeName?: T;
  attendeeEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-groups_select".
 */
export interface AccountGroupsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  type?: T;
  parent?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-accounts_select".
 */
export interface GlAccountsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  group?: T;
  type?: T;
  class?: T;
  openingBalance?: T;
  active?: T;
  allowManualPosting?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-entries_select".
 */
export interface JournalEntriesSelect<T extends boolean = true> {
  date?: T;
  narration?: T;
  status?: T;
  postedAt?: T;
  cleared?: T;
  clearedAt?: T;
  lines?:
    | T
    | {
        account?: T;
        debit?: T;
        credit?: T;
        memo?: T;
        id?: T;
      };
  createdBy?: T;
  tenant?: T;
  referenceDoc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties_select".
 */
export interface PartiesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  taxId?: T;
  address?: T;
  openingBalance?: T;
  donor?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  docType?: T;
  number?: T;
  date?: T;
  party?: T;
  narration?: T;
  status?: T;
  postedAt?: T;
  orderStatus?: T;
  confirmedAt?: T;
  cancelledAt?: T;
  journalEntry?: T;
  referenceTo?: T;
  paymentMethod?: T;
  bankAccount?: T;
  donationPurpose?: T;
  lines?:
    | T
    | {
        item?: T;
        description?: T;
        qty?: T;
        rate?: T;
        amount?: T;
        id?: T;
      };
  journalLines?:
    | T
    | {
        account?: T;
        debit?: T;
        credit?: T;
        memo?: T;
        id?: T;
      };
  taxRate?: T;
  netTotal?: T;
  taxTotal?: T;
  grossTotal?: T;
  createdBy?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doc-sequences_select".
 */
export interface DocSequencesSelect<T extends boolean = true> {
  key?: T;
  lastNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  unit?: T;
  valuationMethod?: T;
  reorderLevel?: T;
  openingStock?: T;
  salePrice?: T;
  purchasePrice?: T;
  active?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  item?: T;
  doc?: T;
  date?: T;
  qtyIn?: T;
  qtyOut?: T;
  unitCost?: T;
  location?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  type?: T;
  active?: T;
  description?: T;
  coverImage?: T;
  enabled?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  domain?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  slug?: T;
  allowPublicRead?: T;
  location?:
    | T
    | {
        address?: T;
        mapUrl?: T;
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  type?: T;
  read?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  tenant?: T;
  fullName?: T;
  email?: T;
  profileImage?: T;
  bio?: T;
  role?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        website?: T;
      };
  status?: T;
  joinedDate?: T;
  phoneNumber?: T;
  memberId?: T;
  user?: T;
  expiryDate?: T;
  idCardDetails?:
    | T
    | {
        bloodGroup?: T;
        emergencyContact?: T;
      };
  membershipType?: T;
  renewalDate?: T;
  lastReceipt?: T;
  paymentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archives_select".
 */
export interface ArchivesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  era?: T;
  year?: T;
  content?: T;
  heroImage?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  tenant?: T;
  chatRoom?: T;
  sender?: T;
  content?: T;
  readBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-rooms_select".
 */
export interface ChatRoomsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types_select".
 */
export interface MembershipTypesSelect<T extends boolean = true> {
  name?: T;
  fee?: T;
  periodMonths?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-statements_select".
 */
export interface BankStatementsSelect<T extends boolean = true> {
  account?: T;
  periodStart?: T;
  periodEnd?: T;
  openingBalance?: T;
  closingBalance?: T;
  rows?:
    | T
    | {
        date?: T;
        description?: T;
        reference?: T;
        amount?: T;
        matchedEntry?: T;
        id?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixed-assets_select".
 */
export interface FixedAssetsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  category?: T;
  purchaseDate?: T;
  purchaseCost?: T;
  salvageValue?: T;
  usefulLifeYears?: T;
  location?: T;
  status?: T;
  depreciationRows?:
    | T
    | {
        date?: T;
        amount?: T;
        journalEntry?: T;
        id?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  eventDate?: T;
  location?: T;
  era?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  impersonatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apikeys_select".
 */
export interface ApikeysSelect<T extends boolean = true> {
  name?: T;
  start?: T;
  prefix?: T;
  key?: T;
  user?: T;
  refillInterval?: T;
  refillAmount?: T;
  lastRefillAt?: T;
  enabled?: T;
  rateLimitEnabled?: T;
  rateLimitTimeWindow?: T;
  rateLimitMax?: T;
  requestCount?: T;
  remaining?: T;
  lastRequest?: T;
  expiresAt?: T;
  permissions?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default accounts used when posting vouchers. Missing accounts block posting until configured.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings".
 */
export interface BillingSetting {
  id: number;
  /**
   * Month and day the fiscal year begins (e.g. 2026-07-16). Unset = calendar year.
   */
  fiscalYearStart?: string | null;
  /**
   * No entries may be posted with a date before this date (period close). Unset = no freeze.
   */
  freezeDate?: string | null;
  /**
   * Accounts Receivable (sales invoices, receipts).
   */
  receivableAccount?: (number | null) | GlAccount;
  /**
   * Accounts Payable (purchase invoices, payments).
   */
  payableAccount?: (number | null) | GlAccount;
  /**
   * Sales / service revenue.
   */
  revenueAccount?: (number | null) | GlAccount;
  /**
   * Purchases / operating expenses.
   */
  expenseAccount?: (number | null) | GlAccount;
  /**
   * Output (sales) / input (purchase) VAT.
   */
  taxAccount?: (number | null) | GlAccount;
  /**
   * Cash on hand (payment/receipt vouchers, petty cash).
   */
  cashAccount?: (number | null) | GlAccount;
  /**
   * Default bank account (payment/receipt vouchers).
   */
  bankAccount?: (number | null) | GlAccount;
  /**
   * Petty cash float (petty cash vouchers).
   */
  pettyCashAccount?: (number | null) | GlAccount;
  /**
   * Membership fee income account (membership receipts).
   */
  membershipFeeAccount?: (number | null) | GlAccount;
  /**
   * Donation income account (donation receipts).
   */
  donationAccount?: (number | null) | GlAccount;
  /**
   * Stock on hand (GRN, delivery challans).
   */
  inventoryAccount?: (number | null) | GlAccount;
  /**
   * Cost of goods sold (delivery challans).
   */
  cogsAccount?: (number | null) | GlAccount;
  /**
   * Sales returns / purchase returns (credit & debit notes).
   */
  returnsAccount?: (number | null) | GlAccount;
  /**
   * Accrued / unbilled purchases (GRN).
   */
  accruedPayableAccount?: (number | null) | GlAccount;
  /**
   * Depreciation expense (asset management).
   */
  depreciationAccount?: (number | null) | GlAccount;
  /**
   * Accumulated depreciation contra-asset (asset management).
   */
  accumulatedDepreciationAccount?: (number | null) | GlAccount;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings_select".
 */
export interface BillingSettingsSelect<T extends boolean = true> {
  fiscalYearStart?: T;
  freezeDate?: T;
  receivableAccount?: T;
  payableAccount?: T;
  revenueAccount?: T;
  expenseAccount?: T;
  taxAccount?: T;
  cashAccount?: T;
  bankAccount?: T;
  pettyCashAccount?: T;
  membershipFeeAccount?: T;
  donationAccount?: T;
  inventoryAccount?: T;
  cogsAccount?: T;
  returnsAccount?: T;
  accruedPayableAccount?: T;
  depreciationAccount?: T;
  accumulatedDepreciationAccount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}